"""add amount field into quotes table

Revision ID: 45fbb584fc97
Revises: 9cabaa8cb557
Create Date: 2025-06-23 14:39:44.834371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45fbb584fc97'
down_revision: Union[str, None] = '9cabaa8cb557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() :
    op.add_column(
        'quotes',
        sa.Column('amount', sa.Float(), nullable=True)
    )


def downgrade() :
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'amount')