export const colorMap = {
  default: {
    light: {
      primary: "text-teal-600",
      primaryDark: "text-emerald-700",
      primaryLightBg: "bg-teal-50",
      primaryFrom: "from-teal-500",
      primaryTo: "to-emerald-500",
      primaryRing: "ring-teal-300",
      hoverFrom: "hover:from-emerald-600",
      hoverTo: "hover:to-teal-600",
      border: "border-teal-500",
      textHover: "hover:text-teal-600",
      borderHover: "hover:border-emerald-500",
    },
    dark: {
      primary: "text-teal-300",
      primaryDark: "text-emerald-300",
      primaryLightBg: "bg-[#1b2c2b]",
      primaryFrom: "from-teal-700",
      primaryTo: "to-emerald-700",
      primaryRing: "ring-teal-400",
      hoverFrom: "hover:from-emerald-600",
      hoverTo: "hover:to-teal-600",
      border: "border-teal-400",
      textHover: "hover:text-teal-300",
      borderHover: "hover:border-teal-400",
    },
  },

  blue: {
    light: {
      primary: "text-blue-600",
      primaryDark: "text-blue-800",
      primaryLightBg: "bg-blue-50",
      primaryFrom: "from-blue-500",
      primaryTo: "to-blue-700",
      primaryRing: "ring-blue-300",
      hoverFrom: "hover:from-blue-600",
      hoverTo: "hover:to-blue-800",
      border: "border-blue-500",
      textHover: "hover:text-blue-600",
      borderHover: "hover:border-blue-700",
    },
    dark: {
      primary: "text-blue-300",
      primaryDark: "text-blue-400",
      primaryLightBg: "bg-[#1e293b]",
      primaryFrom: "from-blue-700",
      primaryTo: "to-blue-900",
      primaryRing: "ring-blue-400",
      hoverFrom: "hover:from-blue-800",
      hoverTo: "hover:to-blue-900",
      border: "border-blue-400",
      textHover: "hover:text-blue-300",
      borderHover: "hover:border-blue-500",
    },
  },

  green: {
    light: {
      primary: "text-green-600",
      primaryDark: "text-green-800",
      primaryLightBg: "bg-green-50",
      primaryFrom: "from-green-500",
      primaryTo: "to-green-700",
      primaryRing: "ring-green-300",
      hoverFrom: "hover:from-green-600",
      hoverTo: "hover:to-green-800",
      border: "border-green-500",
      textHover: "hover:text-green-600",
      borderHover: "hover:border-green-700",
    },
    dark: {
      primary: "text-green-300",
      primaryDark: "text-green-400",
      primaryLightBg: "bg-[#1f2e27]",
      primaryFrom: "from-green-700",
      primaryTo: "to-green-900",
      primaryRing: "ring-green-400",
      hoverFrom: "hover:from-green-800",
      hoverTo: "hover:to-green-900",
      border: "border-green-400",
      textHover: "hover:text-green-300",
      borderHover: "hover:border-green-500",
    },
  },

  brown: {
    light: {
      primary: "text-amber-800",
      primaryDark: "text-yellow-700",
      primaryLightBg: "bg-amber-50",
      primaryFrom: "from-amber-500",
      primaryTo: "to-yellow-700",
      primaryRing: "ring-amber-300",
      hoverFrom: "hover:from-amber-600",
      hoverTo: "hover:to-yellow-800",
      border: "border-amber-500",
      textHover: "hover:text-amber-800",
      borderHover: "hover:border-yellow-700",
    },
    dark: {
      primary: "text-amber-300",
      primaryDark: "text-yellow-300",
      primaryLightBg: "bg-[#1c1917]",
      primaryFrom: "from-amber-700",
      primaryTo: "to-yellow-900",
      primaryRing: "ring-amber-400",
      hoverFrom: "hover:from-amber-800",
      hoverTo: "hover:to-yellow-900",
      border: "border-amber-400",
      textHover: "hover:text-amber-300",
      borderHover: "hover:border-amber-500",
    },
  },

  pink: {
    light: {
      primary: "text-pink-600",
      primaryDark: "text-pink-800",
      primaryLightBg: "bg-pink-50",
      primaryFrom: "from-pink-500",
      primaryTo: "to-pink-700",
      primaryRing: "ring-pink-300",
      hoverFrom: "hover:from-pink-600",
      hoverTo: "hover:to-pink-800",
      border: "border-pink-500",
      textHover: "hover:text-pink-600",
      borderHover: "hover:border-pink-700",
    },
    dark: {
      primary: "text-pink-300",
      primaryDark: "text-pink-400",
      primaryLightBg: "bg-[#3b1f2b]",
      primaryFrom: "from-pink-700",
      primaryTo: "to-pink-900",
      primaryRing: "ring-pink-400",
      hoverFrom: "hover:from-pink-800",
      hoverTo: "hover:to-pink-900",
      border: "border-pink-400",
      textHover: "hover:text-pink-300",
      borderHover: "hover:border-pink-500",
    },
  },

  cyan: {
    light: {
      primary: "text-cyan-600",
      primaryDark: "text-cyan-800",
      primaryLightBg: "bg-cyan-50",
      primaryFrom: "from-cyan-500",
      primaryTo: "to-cyan-700",
      primaryRing: "ring-cyan-300",
      hoverFrom: "hover:from-cyan-600",
      hoverTo: "hover:to-cyan-800",
      border: "border-cyan-500",
      textHover: "hover:text-cyan-600",
      borderHover: "hover:border-cyan-700",
    },
    dark: {
      primary: "text-cyan-300",
      primaryDark: "text-cyan-400",
      primaryLightBg: "bg-[#103944]",
      primaryFrom: "from-cyan-700",
      primaryTo: "to-cyan-900",
      primaryRing: "ring-cyan-400",
      hoverFrom: "hover:from-cyan-800",
      hoverTo: "hover:to-cyan-900",
      border: "border-cyan-400",
      textHover: "hover:text-cyan-300",
      borderHover: "hover:border-cyan-500",
    },
  },

  
  navy: {
    light: {
      primary: "text-indigo-700",
      primaryDark: "text-indigo-900",
      primaryLightBg: "bg-indigo-50",
      primaryFrom: "from-indigo-600",
      primaryTo: "to-indigo-800",
      primaryRing: "ring-indigo-300",
      hoverFrom: "hover:from-indigo-700",
      hoverTo: "hover:to-indigo-900",
      border: "border-indigo-600",
      textHover: "hover:text-indigo-700",
      borderHover: "hover:border-indigo-800",
    },
    dark: {
      primary: "text-indigo-300",
      primaryDark: "text-indigo-400",
      primaryLightBg: "bg-[#1e1b4b]",
      primaryFrom: "from-indigo-800",
      primaryTo: "to-indigo-950",
      primaryRing: "ring-indigo-500",
      hoverFrom: "hover:from-indigo-700",
      hoverTo: "hover:to-indigo-900",
      border: "border-indigo-400",
      textHover: "hover:text-indigo-300",
      borderHover: "hover:border-indigo-500",
    },
  },

  slate: {
    light: {
      primary: "text-slate-700",
      primaryDark: "text-slate-900",
      primaryLightBg: "bg-slate-50",
      primaryFrom: "from-slate-500",
      primaryTo: "to-slate-700",
      primaryRing: "ring-slate-300",
      hoverFrom: "hover:from-slate-600",
      hoverTo: "hover:to-slate-800",
      border: "border-slate-500",
      textHover: "hover:text-slate-700",
      borderHover: "hover:border-slate-800",
    },
    dark: {
      primary: "text-slate-300",
      primaryDark: "text-slate-400",
      primaryLightBg: "bg-slate-800",
      primaryFrom: "from-slate-700",
      primaryTo: "to-slate-900",
      primaryRing: "ring-slate-500",
      hoverFrom: "hover:from-slate-800",
      hoverTo: "hover:to-slate-950",
      border: "border-slate-400",
      textHover: "hover:text-slate-300",
      borderHover: "hover:border-slate-500",
    },
  },

  emerald: {
    light: {
      primary: "text-emerald-600",
      primaryDark: "text-emerald-800",
      primaryLightBg: "bg-emerald-50",
      primaryFrom: "from-emerald-500",
      primaryTo: "to-emerald-700",
      primaryRing: "ring-emerald-300",
      hoverFrom: "hover:from-emerald-600",
      hoverTo: "hover:to-emerald-800",
      border: "border-emerald-500",
      textHover: "hover:text-emerald-600",
      borderHover: "hover:border-emerald-700",
    },
    dark: {
      primary: "text-emerald-300",
      primaryDark: "text-emerald-400",
      primaryLightBg: "bg-[#0f2d2a]",
      primaryFrom: "from-emerald-700",
      primaryTo: "to-emerald-900",
      primaryRing: "ring-emerald-400",
      hoverFrom: "hover:from-emerald-800",
      hoverTo: "hover:to-emerald-900",
      border: "border-emerald-400",
      textHover: "hover:text-emerald-300",
      borderHover: "hover:border-emerald-500",
    },
  },

  wine: {
    light: {
      primary: "text-rose-700",
      primaryDark: "text-rose-900",
      primaryLightBg: "bg-rose-50",
      primaryFrom: "from-rose-500",
      primaryTo: "to-rose-700",
      primaryRing: "ring-rose-300",
      hoverFrom: "hover:from-rose-600",
      hoverTo: "hover:to-rose-800",
      border: "border-rose-500",
      textHover: "hover:text-rose-700",
      borderHover: "hover:border-rose-800",
    },
    dark: {
      primary: "text-rose-300",
      primaryDark: "text-rose-400",
      primaryLightBg: "bg-[#3b1f2f]",
      primaryFrom: "from-rose-700",
      primaryTo: "to-rose-900",
      primaryRing: "ring-rose-400",
      hoverFrom: "hover:from-rose-800",
      hoverTo: "hover:to-rose-900",
      border: "border-rose-400",
      textHover: "hover:text-rose-300",
      borderHover: "hover:border-rose-500",
    },
  },
};
